// frontend-angular/src/app/components/month-view/month-view.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as dayjs from 'dayjs';
import { CalendarEvent, Calendar } from '../../interfaces/calendar-event.interface';


@Component({
  selector: 'app-month-view',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './month-view.component.html',
  styleUrls: ['./month-view.component.scss']
})
export class MonthViewComponent {
  @Input() date!: Date;
  @Input() events: CalendarEvent[] = [];
  @Input() calendars: Calendar[] = [];

  weekDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  getMonthStart(): Date {
    return dayjs(this.date).startOf('month').toDate();
  }

  getMonthEnd(): dayjs.Dayjs {
    return dayjs(this.date).endOf('month');
  }

  getStartDate(): dayjs.Dayjs {
    return dayjs(this.getMonthStart()).startOf('week');
  }

  getEndDate(): dayjs.Dayjs {
    return this.getMonthEnd().endOf('week');
  }

  getDays(): dayjs.Dayjs[] {
    const days: dayjs.Dayjs[] = [];
    const startDate = this.getStartDate();
    const endDate = this.getEndDate();
    let current = startDate;
    
    while (current.isBefore(endDate) || current.isSame(endDate, 'day')) {
      days.push(current);
      current = current.add(1, 'day');
    }
    
    return days;
  }

  getEventsForDate(date: dayjs.Dayjs): CalendarEvent[] {
    return this.events.filter(event => {
      const eventDate = dayjs(event.start_time);
      return eventDate.isSame(date, 'day');
    });
  }

  getEventStyle(event: CalendarEvent): any {
    const calendar = this.calendars.find(c => c.id === event.calendar_id);
    return {
      backgroundColor: calendar?.color || '#4285f4',
    };
  }

  isToday(date: dayjs.Dayjs): boolean {
    return date.isSame(dayjs(), 'day');
  }

  isCurrentMonth(date: dayjs.Dayjs): boolean {
    return date.isSame(this.getMonthStart(), 'month');
  }

  trackByDay(index: number, day: dayjs.Dayjs): string {
    return day.format('YYYY-MM-DD');
  }

  trackByEventId(index: number, event: CalendarEvent): string {
    return event.id;
  }
}

<div class="h-full overflow-auto bg-white">
  <!-- Month header -->
  <div class="sticky top-0 bg-white border-b border-gray-200 z-10 p-4">
    <h1 class="text-2xl font-bold text-gray-900">
      {{ getMonthStart() | date:'MMMM y' }}
    </h1>
  </div>

  <!-- Calendar grid -->
  <div class="p-4">
    <!-- Week day headers -->
    <div class="grid grid-cols-7 gap-px bg-gray-200 mb-1">
      <div
        *ngFor="let day of weekDays"
        class="bg-white p-3 text-center"
      >
        <span class="text-sm font-medium text-gray-700">{{ day }}</span>
      </div>
    </div>

    <!-- Calendar days -->
    <div class="grid grid-cols-7 gap-px bg-gray-200">
      <div
        *ngFor="let day of getDays(); trackBy: trackByDay; let i = index"
        [class]="'bg-white min-h-[120px] p-2 ' + (!isCurrentMonth(day) ? 'bg-gray-50' : '')"
      >
        <!-- Date number -->
        <div [class]="'text-right mb-2 ' + (isToday(day) ? 'bg-yellow-400 text-white w-6 h-6 rounded-full flex items-center justify-center text-sm font-bold' : (isCurrentMonth(day) ? 'text-gray-900' : 'text-gray-400'))">
          {{ isToday(day) ? '' : day.format('D') }}
        </div>
        
        <!-- Events -->
        <div class="space-y-1">
          <div
            *ngFor="let event of getEventsForDate(day).slice(0, 3); trackBy: trackByEventId"
            class="p-1 text-xs text-white rounded overflow-hidden cursor-pointer hover:opacity-90 transition-opacity"
            [ngStyle]="getEventStyle(event)"
            [title]="event.title"
          >
            <div class="truncate">
              {{ event.title }}
            </div>
          </div>
          
          <div
            *ngIf="getEventsForDate(day).length > 3"
            class="text-xs text-gray-500 text-center"
          >
            +{{ getEventsForDate(day).length - 3 }} more
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/components/Calendar/MonthView.tsx
import React from 'react';
import dayjs from 'dayjs';
import { Calendar, Event } from '../../types/calendar';

interface MonthViewProps {
  date: Date;
  events: Event[];
  calendars: Calendar[];
}

const MonthView: React.FC<MonthViewProps> = ({ date, events, calendars }) => {
  const monthStart = dayjs(date).startOf('month');
  const monthEnd = dayjs(date).endOf('month');
  const startDate = monthStart.startOf('week');
  const endDate = monthEnd.endOf('week');
  
  const days = [];
  let current = startDate;
  
  while (current.isBefore(endDate) || current.isSame(endDate, 'day')) {
    days.push(current);
    current = current.add(1, 'day');
  }

  const getEventsForDate = (date: dayjs.Dayjs) => {
    return events.filter(event => {
      const eventDate = dayjs(event.start_time);
      return eventDate.isSame(date, 'day');
    });
  };

  const getEventStyle = (event: Event) => {
    const calendar = calendars.find(c => c.id === event.calendar_id);
    return {
      backgroundColor: calendar?.color || '#4285f4',
    };
  };

  const isToday = (date: dayjs.Dayjs) => {
    return date.isSame(dayjs(), 'day');
  };

  const isCurrentMonth = (date: dayjs.Dayjs) => {
    return date.isSame(monthStart, 'month');
  };

  const weekDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  return (
    <div className="h-full overflow-auto bg-white">
      {/* Month header */}
      <div className="sticky top-0 bg-white border-b border-gray-200 z-10 p-4">
        <h1 className="text-2xl font-bold text-gray-900">
          {monthStart.format('MMMM YYYY')}
        </h1>
      </div>

      {/* Calendar grid */}
      <div className="p-4">
        {/* Week day headers */}
        <div className="grid grid-cols-7 gap-px bg-gray-200 mb-1">
          {weekDays.map((day) => (
            <div key={day} className="bg-white p-3 text-center">
              <span className="text-sm font-medium text-gray-700">{day}</span>
            </div>
          ))}
        </div>

        {/* Calendar days */}
        <div className="grid grid-cols-7 gap-px bg-gray-200">
          {days.map((day, index) => {
            const dayEvents = getEventsForDate(day);
            const isTodayDate = isToday(day);
            const isCurrentMonthDay = isCurrentMonth(day);
            
            return (
              <div
                key={index}
                className={`bg-white min-h-[120px] p-2 ${
                  !isCurrentMonthDay ? 'bg-gray-50' : ''
                }`}
              >
                {/* Date number */}
                <div className={`text-right mb-2 ${
                  isTodayDate 
                    ? 'bg-yellow-400 text-white w-6 h-6 rounded-full flex items-center justify-center text-sm font-bold'
                    : isCurrentMonthDay 
                      ? 'text-gray-900' 
                      : 'text-gray-400'
                }`}>
                  {isTodayDate ? '' : day.format('D')}
                </div>
                
                {/* Events */}
                <div className="space-y-1">
                  {dayEvents.slice(0, 3).map((event, eventIndex) => (
                    <div
                      key={event.id}
                      className="p-1 text-xs text-white rounded overflow-hidden cursor-pointer hover:opacity-90 transition-opacity"
                      style={getEventStyle(event)}
                      title={event.title}
                    >
                      <div className="truncate">
                        {event.title}
                      </div>
                    </div>
                  ))}
                  
                  {dayEvents.length > 3 && (
                    <div className="text-xs text-gray-500 text-center">
                      +{dayEvents.length - 3} more
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default MonthView;
